/**
 * Generated by tsnapi — public API snapshot of `dsh-h3`
 */
// #region Interfaces
export interface HostApp extends H3 {
  on: OnRegistrar<this>;
  all: RouteRegistrar<this>;
  get: RouteRegistrar<this>;
  post: RouteRegistrar<this>;
  put: RouteRegistrar<this>;
  delete: RouteRegistrar<this>;
  patch: RouteRegistrar<this>;
  head: RouteRegistrar<this>;
  options: RouteRegistrar<this>;
  connect: RouteRegistrar<this>;
  trace: RouteRegistrar<this>;
  query: RouteRegistrar<this>;
}
export interface HostServiceInstance<Options = undefined> {
  context: Context;
  options: Options;
}
// #endregion

// #region Types
export type HostRoute = Omit<WebRoute, 'handler'>;
export type HostService<Options = undefined> = (undefined extends Options ? (ctx: Context, options?: Options) => () => void : (ctx: Context, options: Options) => () => void) & {
  __instance?: HostServiceInstance<Options>;
};
// #endregion

// #region Functions
export declare function defineWebServer<Options = undefined>(_: (_: HostApp) => void | HostApp): HostService<Options>;
// #endregion

// #region Referenced (internal)
interface OnRegistrar<T> {
  (_: Method, _: string | HostRoute, _: WebRoute['handler'], _?: RouteOptions): T;
  <RequestT extends EventHandlerRequest = EventHandlerRequest>(_: Method, _: string | HostRoute, _: HTTPHandler<RequestT>, _?: RouteOptions): T;
}
interface RouteRegistrar<T> {
  (_: string | HostRoute, _: WebRoute['handler'], _?: RouteOptions): T;
  <RequestT extends EventHandlerRequest = EventHandlerRequest>(_: string | HostRoute, _: HTTPHandler<RequestT>, _?: RouteOptions): T;
}
// #endregion