/**
 * Generated by tsnapi — public API snapshot of `dsh-h3`
 */
// #region Interfaces
export interface HostServiceInstance<Options = undefined> {
  context: Context;
  options: Options;
}
// #endregion

// #region Types
export type HostService<Options = undefined> = (undefined extends Options ? (ctx: Context, options?: Options) => () => void : (ctx: Context, options: Options) => () => void) & {
  __host_instance?: HostServiceInstance<Options>;
};
// #endregion

// #region Functions
export declare function defineWebServer<Options = undefined>(_: (_: H3) => void | H3): HostService<Options>;
// #endregion