/**
 * Generated by tsnapi — public API snapshot of `dsh-h3/utils`
 */
// #region Functions
export declare function getServerContext<Options>(_: HostService<Options> | H3Event): Context;
export declare function getServerOptions<Options>(_: HostService<Options> | H3Event): Options;
// #endregion