/**
 * Generated by tsnapi — public API snapshot of `dsh-h3/utils`
 */
// #region Functions
export declare function getServerContext<Context$1 = Context>(_: HostService<any> | H3Event): Context$1;
export declare function getServerOptions<Options>(_: HostService<Options> | H3Event): Options;
// #endregion